# Generated by Django 2.0.5 on 2018-05-28 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('question_count', models.PositiveSmallIntegerField()),
                ('language', models.PositiveSmallIntegerField(choices=[(0, 'uz'), (1, 'ru'), (2, 'en')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('mark', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlanish vaqti')),
                ('deadline', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('test_time', models.DurationField(verbose_name='Test vaqti')),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Sana')),
                ('is_multiple_choice', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now=True, verbose_name='Test Boshlangan Vaqt')),
                ('end_time', models.DateTimeField(null=True, verbose_name='Tugallangan vaqt')),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Vaqt')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Choice')),
                ('response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.Response')),
            ],
        ),
        migrations.CreateModel(
            name='Testee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.PositiveSmallIntegerField(choices=[(0, 'uz'), (1, 'ru'), (2, 'en')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TesteeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ManyToManyField(to='assessment.Category')),
            ],
        ),
        migrations.AddField(
            model_name='testee',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.TesteeGroup'),
        ),
        migrations.AddField(
            model_name='testee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selectedchoice',
            name='testee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Testee'),
        ),
        migrations.AddField(
            model_name='response',
            name='choices',
            field=models.ManyToManyField(through='assessment.SelectedChoice', to='assessment.Choice'),
        ),
        migrations.AddField(
            model_name='response',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.Exam'),
        ),
        migrations.AddField(
            model_name='response',
            name='questions',
            field=models.ManyToManyField(to='assessment.Question'),
        ),
        migrations.AddField(
            model_name='response',
            name='testee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Testee'),
        ),
        migrations.AddField(
            model_name='exam',
            name='groups',
            field=models.ManyToManyField(to='assessment.TesteeGroup'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Question'),
        ),
    ]
