# Generated by Django 2.0.5 on 2018-05-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_selectedchoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedchoice',
            name='testee',
        ),
    ]
