# Generated by Django 2.0.5 on 2018-05-23 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('question_count', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('text_ru', models.CharField(max_length=255)),
                ('text_en', models.CharField(max_length=255)),
                ('mark', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlanish vaqti')),
                ('deadline', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('test_time', models.TimeField(verbose_name='Test vaqti')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('text_ru', models.CharField(max_length=255)),
                ('text_en', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Sana')),
                ('is_multiple_choice', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now=True, verbose_name='Test Boshlangan Vaqt')),
                ('end_time', models.DateTimeField(null=True, verbose_name='Tugallangan vaqt')),
                ('is_finished', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Exam')),
                ('questions', models.ManyToManyField(to='polls.Question')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.ManyToManyField(to='polls.Choice')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Response')),
            ],
        ),
        migrations.CreateModel(
            name='Testee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.PositiveSmallIntegerField(choices=[(0, 'uz'), (1, 'ru'), (2, 'en')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TesteeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='testee',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.TesteeGroup'),
        ),
        migrations.AddField(
            model_name='testee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selectedchoices',
            name='testee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Testee'),
        ),
        migrations.AddField(
            model_name='response',
            name='testee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Testee'),
        ),
        migrations.AddField(
            model_name='exam',
            name='groups',
            field=models.ManyToManyField(to='polls.TesteeGroup'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
