# Generated by Django 2.0.5 on 2018-05-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testeegroup',
            name='category',
            field=models.ManyToManyField(to='polls.Category'),
        ),
    ]
