# Generated by Django 2.0.5 on 2018-05-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180524_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='test_time',
            field=models.DurationField(verbose_name='Test vaqti'),
        ),
    ]
