# Generated by Django 2.0.5 on 2018-05-25 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20180524_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_ru',
        ),
    ]
