# Generated by Django 2.0.5 on 2018-05-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20180525_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(0, 'uz'), (1, 'ru'), (2, 'en')], default=0),
        ),
    ]
