# Generated by Django 2.0.5 on 2018-05-25 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_category_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Vaqt')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Choice')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Response')),
                ('testee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Testee')),
            ],
        ),
        migrations.RemoveField(
            model_name='selectedchoices',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='selectedchoices',
            name='response',
        ),
        migrations.RemoveField(
            model_name='selectedchoices',
            name='testee',
        ),
        migrations.DeleteModel(
            name='SelectedChoices',
        ),
        migrations.AddField(
            model_name='response',
            name='choices',
            field=models.ManyToManyField(through='polls.SelectedChoice', to='polls.Choice'),
        ),
    ]
