# Generated by Django 2.0.5 on 2018-05-25 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20180525_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedchoice',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Response'),
        ),
    ]
